server:
  port: 9999
  
spring:
  application:
    name: jian_mu
  config:
    import: classpath:application-local.yml,
                      business/web_socket/web-socket.yml
  
  # 数据源
  datasource:
    dynamic:
      primary: lmyxlf
      strict: false
      datasource:
        lmyxlf:
          # mysql 版本 5.7 以上
          url: jdbc:mysql://${mysql.MYSQL_HOST:mysql:3306}/${mysql.MYSQL_DATABASE:lmyxlf}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
          # mysql 版本 5.7 以下
#          url: jdbc:mysql://${mysql.MYSQL_HOST:mysql:3306}/${mysql.MYSQL_DATABASE:lmyxlf}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: root
          password: ${mysql.MYSQL_PASSWORD:lmyxlf}
          # mysql 版本 5.7 以上
          driver-class-name: com.mysql.cj.jdbc.Driver
          # mysql 版本 5.7 以下
#          driver-class-name: com.mysql.jdbc.Driver
          
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          password: ${redis.REDIS_PASSWORD:lmyxlf}
          subscriptionsPerConnection: 5
          clientName: lmyxlf
          address: redis://${redis.REDIS_HOST:redis:6379}
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 8
          connectionMinimumIdleSize: 8
          connectionPoolSize: 16
          database: 0
          dnsMonitoringInterval: 5000
        threads: 4
        nettyThreads: 4
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode : "NIO"
    
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
#  type-enums-package:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    cache-enabled: true
    map-underscore-to-camel-case: true

logging:
  config: classpath:log/logback-spring.xml
  
# 是否开启swagger文档
swagger:
  enabled: ${SWAGGER_ENABLE:true}