server:
  port: 9999
  shutdown: graceful
  
spring:
  application:
    name: jian_mu
  # 不返回 null 字段
  jackson:
    default-property-inclusion: non_null
  # banner 图
  banner:
    location: classpath:static/banner.txt
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: global/i18n/messages
  config:
    import: classpath:application-local.yml,
                      business/web_socket/web-socket.yml,
                      business/own_tools/own-tools.yml,
                      business/batch_invitation/batch-invitation.yml,
                      admin/admin.yml
  
  # 数据源
  datasource:
    dynamic:
      primary: lmyxlf
      strict: false
      datasource:
        lmyxlf:
          # mysql 版本 5.7 以上
          url: jdbc:mysql://${mysql.MYSQL_HOST:mysql:3306}/${mysql.MYSQL_DATABASE_1:lmyxlf}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
          # mysql 版本 5.7 以下
#          url: jdbc:mysql://${mysql.MYSQL_HOST:mysql:3306}/${mysql.MYSQL_DATABASE_1:lmyxlf}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: root
          password: ${mysql.MYSQL_PASSWORD:lmyxlf}
          # mysql 版本 5.7 以上
          driver-class-name: com.mysql.cj.jdbc.Driver
          # mysql 版本 5.7 以下
#          driver-class-name: com.mysql.jdbc.Driver
        admin:
          # mysql 版本 5.7 以上
          url: jdbc:mysql://${mysql.MYSQL_HOST:mysql:3306}/${mysql.MYSQL_DATABASE_2:admin}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
          # mysql 版本 5.7 以下
#          url: jdbc:mysql://${mysql.MYSQL_HOST:mysql:3306}/${mysql.MYSQL_DATABASE_2:admin}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: root
          password: ${mysql.MYSQL_PASSWORD:lmyxlf}
          # mysql 版本 5.7 以上
          driver-class-name: com.mysql.cj.jdbc.Driver
          # mysql 版本 5.7 以下
#          driver-class-name: com.mysql.jdbc.Driver
          
  redis:
    host: redis://${redis.REDIS_HOST:redis:6379}
    password: ${redis.REDIS_PASSWORD:lmyxlf}
    
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
#  type-enums-package:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    cache-enabled: true
    map-underscore-to-camel-case: true

logging:
  config: classpath:log/logback-spring.xml
  
# 是否开启swagger文档
swagger:
  enabled: ${SWAGGER_ENABLE:true}
  
# xxl-job
xxl:
  job:
    admin:
      # xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://${xxl.job.admin.XXL_JOB_ADMIN_HOST:xxl-job-admin:10002}/xxl-job-admin
    # xxl-job, access token
    accessToken: default_token
    executor:
      # xxl-job executor appname
      appname: lmyxlf
      # xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
      address:
      # xxl-job executor server-info
      ip:
      port: 10001
      # xxl-job executor log-path
      logpath: ./jian_mu/logs/xxl_job/executor
      # xxl-job executor log-retention-days
      logretentiondays: 9