services:
  jian-mu:
    build:
      context: ./jian_mu
      dockerfile: Dockerfile
    image: jian-mu
    container_name: jian-mu
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - "./jian_mu/logs:/jian_mu/logs"
    networks:
      - jian-mu-net
    depends_on:
      - mysql
      - redis
      - xxl-job-admin
  
  mysql:
    image: mysql:8.0.38
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: lmyxlf
    volumes:
      - "./mysql/conf:/etc/mysql/conf.d"
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/init:/docker-entrypoint-initdb.d"
    networks:
      - jian-mu-net
      
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    # 密码
    command: redis-server --requirepass lmyxlf
    volumes:
      - ./redis/data:/data
      - ./jian_mu/logs/redis:/logs
    networks:
      - jian-mu-net
  
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/html:/usr/share/nginx/html"
      - "./jian_mu/logs/nginx:/var/log/nginx"
    depends_on:
      - jian-mu
    networks:
      - jian-mu-net
      
  xxl-job-admin:
    build:
      context: ./xxl_job
      dockerfile: Dockerfile
    image: xuxueli/xxl-job-admin:2.4.1
    container_name: xxl-job-admin
    restart: always
    ports:
      - "10002:10002"
    environment:
      # 设置启动参数
      PARAMS:
        --server.port=10002
        --spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
        --spring.datasource.username=root
        --spring.datasource.password=lmyxlf
        --xxl.job.logretentiondays=9
    volumes:
      - "./jian_mu/logs/xxl_job:/data/applogs/xxl-job"
    networks:
      - jian-mu-net
    depends_on:
      - mysql
      
networks:
  jian-mu-net:
    name: jian-mu-net